### ISSUE TITLE
Why the restrictive license?

### ISSUE THREAD

**Issue by lbmn** [FedericoCeratto/nimi3status#1]
One of Nim's top advocacy points is the degree to which it and its module ecosystem is [copyfree](http://copyfree.org/standard/) - anyone can use it for whatever purpose without becoming subjected to pages and pages of legal threats that no one *really* understands...

Nim uses the [MIT license](https://writing.kemitchell.com/2016/09/21/MIT-License-Line-by-Line.html) for all of its compiler, stdlib, and tooling - and that is also what nimble recommends as the default for new modules.

The same also applies to i3wm, which uses the [BSD 3-clause license](https://github.com/i3/i3/blob/next/LICENSE).

What are your reasons for using the extremely restrictive GPLv3 license?  A lot of people (including myself) will avoid your software [on philosophical grounds](http://copyfree.org) if you do...

**Comment by apotheon** [comment]
I have to agree with @lbmn on this.  I use i3, and thought this looked interesting, but the license is a turn-off.  I prefer software that uses a license under which I'd be willing to contribute improvements, and when the original i3status uses a more friendly license I think I'll just stick with the original i3status.

**Comment by FedericoCeratto** [comment]
I select licenses based on the use-case of the library or application in order to protect developers and users. GPL discourages patent trolling, "tivoization" and uncooperative behavior from organization that don't care about giving back to upstream projects.
